import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import { parseArgs } from 'node:util';
import { testConnection } from '../lib/test-connection.js';
import { runMigrations } from '../database/migrate.js';
import { createDb } from '../database/client.js';
import { findOrCreateByName } from '../modules/auth/auth.service.js';
import { joinByCode } from '../modules/projects/project.service.js';

interface CliArgs {
  readonly dbUrl: string | undefined;
  readonly name: string | undefined;
  readonly joinCode: string | undefined;
  readonly ssl: boolean;
  readonly force: boolean;
}

function parseCliArgs(): CliArgs {
  const { values } = parseArgs({
    options: {
      'db-url': { type: 'string' },
      name: { type: 'string' },
      'join-code': { type: 'string' },
      ssl: { type: 'boolean', default: true },
      'no-ssl': { type: 'boolean', default: false },
      force: { type: 'boolean', default: false },
    },
    strict: false,
  });

  return {
    dbUrl: values['db-url'] as string | undefined,
    name: values['name'] as string | undefined,
    joinCode: values['join-code'] as string | undefined,
    ssl: values['no-ssl'] === true ? false : ((values['ssl'] as boolean | undefined) ?? true),
    force: (values['force'] as boolean | undefined) ?? false,
  };
}

function writeEnvFile(options: {
  readonly dbUrl: string;
  readonly ssl: boolean;
  readonly jwtSecret: string;
}): void {
  const envContent = `# Generated by pnpm setup:team
PORT=3001
HOST=0.0.0.0
NODE_ENV=development

DATABASE_URL=${options.dbUrl}
DATABASE_SSL=${options.ssl}
RUN_MIGRATIONS=true

JWT_SECRET=${options.jwtSecret}
JWT_EXPIRES_IN=7d
FRONTEND_URL=http://localhost:5173
`;

  const envPath = path.join(import.meta.dirname, '../../.env');
  fs.writeFileSync(envPath, envContent, 'utf-8');
}

async function main() {
  const args = parseCliArgs();
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log('');
  console.log('=== ContextSync Team Setup ===');
  console.log('');

  try {
    // 1. Database URL
    const dbUrl = args.dbUrl ?? (await rl.question('Database URL: ')).trim();
    if (!dbUrl) {
      console.error('Database URL is required.');
      process.exit(1);
    }

    // 2. Test connection (try SSL first, then without)
    let ssl = args.ssl;
    console.log('Testing connection...');
    let test = await testConnection(dbUrl, ssl);

    if (!test.success && ssl) {
      console.log('SSL connection failed, retrying without SSL...');
      ssl = false;
      test = await testConnection(dbUrl, ssl);
    }

    if (!test.success) {
      console.error(`Connection failed: ${test.error}`);
      console.error('Please check your Database URL and try again.');
      process.exit(1);
    }

    console.log(`Connected! (${test.version ?? 'unknown'}, ${test.latencyMs}ms)`);

    // 3. Run migrations
    console.log('Running migrations...');
    await runMigrations({ connectionString: dbUrl, sslEnabled: ssl });

    // 4. Write .env file
    const envPath = path.join(import.meta.dirname, '../../.env');
    if (fs.existsSync(envPath) && !args.force) {
      const overwrite = await rl.question('apps/api/.env already exists. Overwrite? [y/N] ');
      if (overwrite.toLowerCase() !== 'y') {
        console.log('Keeping existing .env file.');
      } else {
        writeEnvFile({ dbUrl, ssl, jwtSecret: crypto.randomBytes(48).toString('base64') });
        console.log('Created apps/api/.env');
      }
    } else {
      writeEnvFile({ dbUrl, ssl, jwtSecret: crypto.randomBytes(48).toString('base64') });
      console.log('Created apps/api/.env');
    }

    // 5. Create DB instance for service calls
    const db = createDb({ connectionString: dbUrl, ssl });

    try {
      // 6. User identification
      const name = args.name ?? (await rl.question('Your name: ')).trim();
      if (!name) {
        console.error('Name is required.');
        process.exit(1);
      }

      const identifyResult = await findOrCreateByName(db, name);
      const user = identifyResult.users[0];
      if (!user) {
        console.error('Failed to create user.');
        process.exit(1);
      }

      if (identifyResult.created) {
        console.log(`Created user: ${user.name}`);
      } else {
        console.log(`Welcome back, ${user.name}!`);
      }

      // 7. Join Code (optional)
      const rawCode = args.joinCode ?? (await rl.question('Join Code (Enter to skip): ')).trim();
      if (rawCode) {
        try {
          const project = await joinByCode(db, rawCode.toUpperCase(), user.id);
          console.log(`Joined project: "${project.name}"`);
        } catch (err) {
          const message = err instanceof Error ? err.message : 'Failed to join project';
          console.error(`Join failed: ${message}`);
        }
      }
    } finally {
      await db.destroy();
    }

    // 8. Done
    console.log('');
    console.log('Setup complete! Run: pnpm dev');
    console.log('  API  -> http://localhost:3001');
    console.log('  Web  -> http://localhost:5173');
    console.log('');
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error('Setup failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
