import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import { parseArgs } from 'node:util';
import { testConnection } from '../lib/test-connection.js';
import { runMigrations } from '../database/migrate.js';
import { createDb } from '../database/client.js';
import { findOrCreateByName } from '../modules/auth/auth.service.js';
import { joinByCode } from '../modules/projects/project.service.js';

const API_DIR = path.join(import.meta.dirname, '../..');
const DEFAULT_API_PORT = 3001;
const DEFAULT_WEB_PORT = 5173;
const PROFILE_API_PORT_START = 3101;
const PROFILE_WEB_PORT_START = 5273;

interface CliArgs {
  readonly dbUrl: string | undefined;
  readonly name: string | undefined;
  readonly joinCode: string | undefined;
  readonly ssl: boolean;
  readonly force: boolean;
}

export interface PortPair {
  readonly apiPort: number;
  readonly webPort: number;
}

function parseCliArgs(): CliArgs {
  const { values } = parseArgs({
    options: {
      'db-url': { type: 'string' },
      name: { type: 'string' },
      'join-code': { type: 'string' },
      ssl: { type: 'boolean', default: true },
      'no-ssl': { type: 'boolean', default: false },
      force: { type: 'boolean', default: false },
    },
    strict: false,
  });

  return {
    dbUrl: values['db-url'] as string | undefined,
    name: values['name'] as string | undefined,
    joinCode: values['join-code'] as string | undefined,
    ssl: values['no-ssl'] === true ? false : ((values['ssl'] as boolean | undefined) ?? true),
    force: (values['force'] as boolean | undefined) ?? false,
  };
}

export function toProfileName(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 30);
}

function parsePortFromEnvFile(filePath: string, key: string): number | undefined {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(new RegExp(`^${key}=(\\d+)`, 'm'));
    return match ? Number(match[1]) : undefined;
  } catch {
    return undefined;
  }
}

function collectUsedPorts(): ReadonlySet<number> {
  const used = new Set<number>();
  used.add(DEFAULT_API_PORT);
  used.add(DEFAULT_WEB_PORT);

  const defaultEnvPath = path.join(API_DIR, '.env');
  const defaultApiPort = parsePortFromEnvFile(defaultEnvPath, 'PORT');
  const defaultWebPort = parsePortFromEnvFile(defaultEnvPath, 'VITE_PORT');
  if (defaultApiPort) used.add(defaultApiPort);
  if (defaultWebPort) used.add(defaultWebPort);

  const files = fs
    .readdirSync(API_DIR)
    .filter((f) => f.startsWith('.env.') && f !== '.env.example');
  for (const file of files) {
    const filePath = path.join(API_DIR, file);
    const apiPort = parsePortFromEnvFile(filePath, 'PORT');
    const webPort = parsePortFromEnvFile(filePath, 'VITE_PORT');
    if (apiPort) used.add(apiPort);
    if (webPort) used.add(webPort);
  }

  return used;
}

export function allocatePorts(): PortPair {
  const used = collectUsedPorts();
  let apiPort = PROFILE_API_PORT_START;
  let webPort = PROFILE_WEB_PORT_START;

  while (used.has(apiPort)) {
    apiPort += 1;
  }
  while (used.has(webPort)) {
    webPort += 1;
  }

  return { apiPort, webPort };
}

export function buildEnvContent(options: {
  readonly dbUrl: string;
  readonly ssl: boolean;
  readonly jwtSecret: string;
  readonly apiPort: number;
  readonly webPort: number;
}): string {
  return `# Generated by pnpm setup:team
PORT=${options.apiPort}
HOST=0.0.0.0
NODE_ENV=development

DATABASE_URL=${options.dbUrl}
DATABASE_SSL=${options.ssl}
RUN_MIGRATIONS=true

JWT_SECRET=${options.jwtSecret}
JWT_EXPIRES_IN=7d
FRONTEND_URL=http://localhost:${options.webPort}
VITE_PORT=${options.webPort}
`;
}

function writeEnvToFile(filePath: string, content: string): void {
  fs.writeFileSync(filePath, content, 'utf-8');
}

async function main() {
  const args = parseCliArgs();
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log('');
  console.log('=== ContextSync Team Setup ===');
  console.log('');

  try {
    // 1. Database URL
    const dbUrl = args.dbUrl ?? (await rl.question('Database URL: ')).trim();
    if (!dbUrl) {
      console.error('Database URL is required.');
      process.exit(1);
    }

    // 2. Test connection (try SSL first, then without)
    let ssl = args.ssl;
    console.log('Testing connection...');
    let test = await testConnection(dbUrl, ssl);

    if (!test.success && ssl) {
      console.log('SSL connection failed, retrying without SSL...');
      ssl = false;
      test = await testConnection(dbUrl, ssl);
    }

    if (!test.success) {
      console.error(`Connection failed: ${test.error}`);
      console.error('Please check your Database URL and try again.');
      process.exit(1);
    }

    console.log(`Connected! (${test.version ?? 'unknown'}, ${test.latencyMs}ms)`);

    // 3. Run migrations
    console.log('Running migrations...');
    await runMigrations({ connectionString: dbUrl, sslEnabled: ssl });

    // 4. Create DB instance for service calls
    const db = createDb({ connectionString: dbUrl, ssl });
    let profileName: string | null = null;

    try {
      // 5. User identification
      const name = args.name ?? (await rl.question('Your name: ')).trim();
      if (!name) {
        console.error('Name is required.');
        process.exit(1);
      }

      const identifyResult = await findOrCreateByName(db, name);
      const user = identifyResult.users[0];
      if (!user) {
        console.error('Failed to create user.');
        process.exit(1);
      }

      if (identifyResult.created) {
        console.log(`Created user: ${user.name}`);
      } else {
        console.log(`Welcome back, ${user.name}!`);
      }

      // 6. Join Code (optional) → derive profile name from project
      const rawCode = args.joinCode ?? (await rl.question('Join Code (Enter to skip): ')).trim();
      if (rawCode) {
        try {
          const project = await joinByCode(db, rawCode.toUpperCase(), user.id);
          console.log(`Joined project: "${project.name}"`);
          profileName = toProfileName(project.name);
        } catch (err) {
          const message = err instanceof Error ? err.message : 'Failed to join project';
          console.error(`Join failed: ${message}`);
        }
      }
    } finally {
      await db.destroy();
    }

    // 7. Write env file
    const jwtSecret = crypto.randomBytes(48).toString('base64');
    const ports = profileName
      ? allocatePorts()
      : { apiPort: DEFAULT_API_PORT, webPort: DEFAULT_WEB_PORT };
    const envFileName = profileName ? `.env.${profileName}` : '.env';
    const envPath = path.join(API_DIR, envFileName);
    const envContent = buildEnvContent({ dbUrl, ssl, jwtSecret, ...ports });

    if (fs.existsSync(envPath) && !args.force) {
      const overwrite = await rl.question(
        `apps/api/${envFileName} already exists. Overwrite? [y/N] `,
      );
      if (overwrite.toLowerCase() !== 'y') {
        console.log(`Keeping existing ${envFileName} file.`);
      } else {
        writeEnvToFile(envPath, envContent);
        console.log(`Created apps/api/${envFileName}`);
      }
    } else {
      writeEnvToFile(envPath, envContent);
      console.log(`Created apps/api/${envFileName}`);
    }

    // 8. Done
    console.log('');
    if (profileName) {
      console.log(`Setup complete! Run: pnpm dev:profile ${profileName}`);
    } else {
      console.log('Setup complete! Run: pnpm dev');
    }
    console.log(`  API  -> http://localhost:${ports.apiPort}`);
    console.log(`  Web  -> http://localhost:${ports.webPort}`);
    console.log('');
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error('Setup failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
